<?php

/**
 * @file
 * Contains entity_counter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_counter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_counter module.
    case 'help.page.entity_counter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function entity_counter_theme($existing, $type, $theme, $path) {
  return [
    'entity_counter' => [
      'variables' => [
        'entities' => [],
      ],
    ],
  ];
}
