<?php

/**
 * @file
 * Contains pagina_colorata.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pagina_colorata_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pagina_colorata module.
    case 'help.page.pagina_colorata':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bellissime pagine colorate per tutti.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pagina_colorata_theme($existing, $type, $theme, $path) {
  return [
    'pagina_colorata' => [
      'variables' => [
        'colors' => [],
      ],
    ],
  ];
}
